services:

  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: didgksehd
      POSTGRES_DB: washhub
      POSTGRES_HOST: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-networks

  nestjs_api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - NODE_OPTIONS=--max-old-space-size=2048
    deploy:
      resources:
        limits:
          memory: 2g
    networks:
      - backend-networks


networks:
  backend-networks:

volumes:
  postgres-data:

